Add ZAP baseline test to CircleCI flow (#1)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,6 +28,22 @@ jobs:
             MIX_ENV=test mix do deps.get, ecto.create, test
 
       - run:
+          name: Run application using Docker compose
+          command: cd docker && docker-compose up -d
+
+      - run:
+          name: ZAP baseline test of application
+          # Only fail on error code 1, which indicates at least one FAIL was found;
+          # error codes 2 & 3 indicate WARN or other, and should not break the run.
+          command: |
+            (
+              docker pull owasp/zap2docker-weekly && \
+              docker run -t --network docker_sdo-phenix owasp/zap2docker-weekly \
+                zap-baseline.py -t http://sdo-phenix:4000/ || \
+              if [ $? -ne 1 ]; then exit 0; else exit 1; fi
+            )
+
+      - run:
           name: Build and push Docker image
           command: |
             if [ "$CIRCLE_BRANCH" == "master" ]; then
