add ZAP baseline test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,10 +28,26 @@ jobs:
             MIX_ENV=test mix do deps.get, ecto.create, test
 
       - run:
+          name: Run application in background
+          command: cd docker; docker-compose up
+          background: true
+
+      - run:
+          name: ZAP baseline test of application
+          # Only fail on error code 1, which indicates at least one FAIL was found;
+          # error codes 2 & 3 indicate WARN or other, and should not break the run.
+          command: |
+            (
+              docker pull owasp/zap2docker-weekly && \
+              docker run -t owasp/zap2docker-weekly \
+                zap-baseline.py -t http://host.docker.internal:4000/ || \
+              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+            )
+
+      - run:
           name: Build and push Docker image
           command: |
             if [ "$CIRCLE_BRANCH" == "master" ]; then
-              docker build -t $DOCKER_USER/$CIRCLE_PROJECT_REPONAME .
               echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
               docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME
             fi
